// Chapter config + i18n strings — ES module version of data.js

export const CHAPTERS = [
  { id: "equations",       icon: "Sigma",        itemCount: 14 },
  { id: "vectors",         icon: "MoveUpRight",  itemCount: 9 },
  { id: "lines",           icon: "Slash",        itemCount: 8 },
  { id: "matrix",          icon: "Grid3x3",      itemCount: 6 },
  { id: "transformations", icon: "Shapes",       itemCount: 9 },
  { id: "curves",          icon: "Spline",       itemCount: 7 },
  { id: "areas",           icon: "SquareDashed", itemCount: 8 },
  { id: "interpolation",   icon: "Activity",     itemCount: 4 },
  { id: "trigonometry",    icon: "Waves",        itemCount: 8 },
  { id: "intersections",   icon: "GitMerge",     itemCount: 9 },
] as const;

export type ChapterId = typeof CHAPTERS[number]['id'];

export const EQUATION_ITEMS = [
  { id: "degree1",     key: "Degree 1" },
  { id: "degree2",     key: "Degree 2" },
  { id: "degree3",     key: "Degree 3" },
  { id: "degree4",     key: "Degree 4" },
  { id: "system2",     key: "System 2×2" },
  { id: "system3",     key: "System 3+" },
  { id: "inequations", key: "Inequations" },
];

export const VECTOR_ITEMS = [
  { id: "cartesian",  key: "Cartesian system" },
  { id: "polar",      key: "Polar system" },
  { id: "scalar",     key: "Multiply by scalar" },
  { id: "sum",        key: "Sum of vectors" },
  { id: "dot",        key: "Dot product" },
  { id: "cross",      key: "Cross product" },
  { id: "midpoint",   key: "Midpoint" },
  { id: "barycenter", key: "Barycenter" },
  { id: "system",     key: "Solve linear system" },
];

export const INTERSECTION_ITEMS = [
  { id: "intersegments",     key: "Intersect segments" },
  { id: "lineinter",         key: "Line intersection" },
  { id: "interlinecircle",   key: "Line-circle intersection" },
  { id: "intersegmentquadra", key: "Segment-quadratic intersection" },
  { id: "intersegmentcubic",  key: "Segment-cubic intersection" },
  { id: "intercircles",      key: "Circle-circle intersection" },
  { id: "interdisks",        key: "Disk intersection" },
  { id: "interpolygons",     key: "Polygon intersection" },
  { id: "unionpolygons",     key: "Polygon union" },
];

export type Lang = 'es' | 'en';

export const STRINGS = {
  es: {
    appName: "ArtMath",
    appSuffix: "matemáticas",
    nav: {
      library: "Biblioteca",
      saved: "Guardados",
      help: "Ayuda",
      formulary: "Formulario",
      search: "Buscar capítulos, conceptos…",
      shortcut: "⌘ K",
    },
    chapters: {
      equations:       { title: "Ecuaciones",       blurb: "Grados 1·2·3·4 — sistemas e inecuaciones" },
      vectors:         { title: "Vectores",         blurb: "Coordenadas, suma, producto escalar y vectorial" },
      lines:           { title: "Rectas",           blurb: "Ecuación, paralela, perpendicular, intersección" },
      matrix:          { title: "Matrices",         blurb: "Suma, producto, inversa" },
      transformations: { title: "Transformaciones", blurb: "Afines y matriciales — composición e inversa" },
      curves:          { title: "Curvas",           blurb: "Círculo, elipse, splines de Bézier·Hermite·Cardinal" },
      areas:           { title: "Área y longitud",  blurb: "Áreas y longitudes de figuras y curvas" },
      interpolation:   { title: "Interpolación",    blurb: "Lineal · Bézier · Hermite · Cardinal" },
      trigonometry:    { title: "Trigonometría",    blurb: "Funciones trigonométricas y sus usos" },
      intersections:   { title: "Intersecciones",   blurb: "Segmentos, rectas, círculos, polígonos" },
    },
    landing: {
      eyebrow: "Biblioteca interactiva",
      title: "Matemáticas Visual Interactivas",
      sub: "Una biblioteca visual de los temas clásicos de geometría y álgebra. Arrastra puntos, mira la fórmula, lee el SVG. Sin lecciones largas — figuras manipulables.",
      cta: "Empezar por Vectores",
      ctaAlt: "Ver el formulario",
      stats: [
        { n: "10",     l: "capítulos" },
        { n: "120",    l: "ejemplos interactivos" },
        { n: "90",     l: "fichas de fórmulas" },
        { n: "ES · EN", l: "bilingüe" },
      ],
      featured: "Capítulos",
      todayHint: "Continúa donde lo dejaste",
    },
    chapter: {
      tabFormula: "Fórmula",
      tabExplore: "Explorar",
      tabSvg: "",
      inspector: "Inspector",
      inspectorHint: "Arrastra los puntos rojos para recalcular.",
      derivation: "Derivación",
      step: "Paso",
      of: "de",
      reset: "Reiniciar",
      copy: "",
      share: "Enlace compartible",
      drag: "Arrastra",
      formulaTitle: "Suma de vectores",
      formulaBody: "Dado un vector u y un vector v en el plano, su suma es el vector cuyas componentes son la suma componente a componente.",
      derivationSteps: [
        "Sean u = (u₁, u₂) y v = (v₁, v₂) en ℝ².",
        "Definimos w = u + v como w = (u₁ + v₁, u₂ + v₂).",
        "Geométricamente: regla del paralelogramo — trasladamos v al extremo de u.",
        "El vector w une el origen con el extremo del v trasladado.",
        "La suma es conmutativa: u + v = v + u.",
      ],
      eqFormulaTitle: "Ecuación de segundo grado",
      eqFormulaBody: "Una ecuación cuadrática ax² + bx + c = 0 tiene hasta dos raíces reales. El discriminante Δ = b² − 4ac determina cuántas y qué tipo de soluciones existen.",
      eqDiscPos:  "Dos raíces reales",
      eqDiscZero: "Una raíz doble",
      eqDiscNeg:  "Sin raíces reales",
      eqRoots:    "Raíces",
      eqVertex:   "Vértice",
      eqDiscriminant: "Discriminante",
      eqCoefficients: "Coeficientes",
      eqDerivation: [
        "Partimos de la forma general ax² + bx + c = 0.",
        "Calculamos el discriminante Δ = b² − 4ac.",
        "Si Δ > 0, hay dos raíces reales x = (−b ± √Δ) / 2a.",
        "Si Δ = 0, hay una raíz doble x = −b / 2a.",
        "Si Δ < 0, las raíces son complejas conjugadas.",
        "El vértice de la parábola está en x = −b / 2a.",
      ],
    },
  },
  en: {
    appName: "ArtMath",
    appSuffix: "math",
    nav: {
      library: "Library",
      saved: "Saved",
      help: "Help",
      formulary: "Formulary",
      search: "Search chapters, concepts…",
      shortcut: "⌘ K",
    },
    chapters: {
      equations:       { title: "Equations",       blurb: "Degree 1·2·3·4 — systems and inequations" },
      vectors:         { title: "Vectors",         blurb: "Coordinates, sum, dot and cross product" },
      lines:           { title: "Lines",           blurb: "Equation, parallel, perpendicular, intersection" },
      matrix:          { title: "Matrix",          blurb: "Addition, product, inverse" },
      transformations: { title: "Transformations", blurb: "Affine & matrix — composition, inverse" },
      curves:          { title: "Curves",          blurb: "Circle, ellipse, Bézier·Hermite·Cardinal splines" },
      areas:           { title: "Area & length",   blurb: "Areas and curve lengths" },
      interpolation:   { title: "Interpolation",   blurb: "Linear · Bézier · Hermite · Cardinal" },
      trigonometry:    { title: "Trigonometry",    blurb: "Trig functions and their uses" },
      intersections:   { title: "Intersections",   blurb: "Segments, lines, circles, polygons" },
    },
    landing: {
      eyebrow: "Interactive library",
      title: "Math that moves when you touch it.",
      sub: "A visual library of classic geometry and algebra. Drag points, see the formula, read the SVG. No long lectures — just figures you can manipulate.",
      cta: "Start with Vectors",
      ctaAlt: "Open the formulary",
      stats: [
        { n: "10",      l: "chapters" },
        { n: "120",     l: "interactive examples" },
        { n: "90",      l: "formula sheets" },
        { n: "EN · ES", l: "bilingual" },
      ],
      featured: "Chapters",
      todayHint: "Pick up where you left off",
    },
    chapter: {
      tabFormula: "Formula",
      tabExplore: "Explore",
      tabSvg: "Use with SVG",
      inspector: "Inspector",
      inspectorHint: "Drag the red points to recompute.",
      derivation: "Derivation",
      step: "Step",
      of: "of",
      reset: "Reset",
      copy: "Copy SVG",
      share: "Shareable link",
      drag: "Drag",
      formulaTitle: "Sum of vectors",
      formulaBody: "Given a vector u and a vector v in the plane, their sum is the vector whose components are the component-wise sum.",
      derivationSteps: [
        "Let u = (u₁, u₂) and v = (v₁, v₂) in ℝ².",
        "Define w = u + v as w = (u₁ + v₁, u₂ + v₂).",
        "Geometrically: parallelogram rule — translate v to the tip of u.",
        "The vector w joins the origin to the tip of the translated v.",
        "Addition is commutative: u + v = v + u.",
      ],
      eqFormulaTitle: "Quadratic equation",
      eqFormulaBody: "A quadratic ax² + bx + c = 0 has up to two real roots. The discriminant Δ = b² − 4ac determines how many — and what kind of — solutions exist.",
      eqDiscPos:  "Two real roots",
      eqDiscZero: "One double root",
      eqDiscNeg:  "No real roots",
      eqRoots:    "Roots",
      eqVertex:   "Vertex",
      eqDiscriminant: "Discriminant",
      eqCoefficients: "Coefficients",
      eqDerivation: [
        "Start from the general form ax² + bx + c = 0.",
        "Compute the discriminant Δ = b² − 4ac.",
        "If Δ > 0, there are two real roots x = (−b ± √Δ) / 2a.",
        "If Δ = 0, there is one double root x = −b / 2a.",
        "If Δ < 0, the roots are complex conjugates.",
        "The parabola's vertex sits at x = −b / 2a.",
      ],
    },
  },
} as const;

export type StringsType = typeof STRINGS;
